// Generated by pnpm generate:scoped; do not edit.
import type { CompiledOpenAPIMetadata } from '../../src/index.js';
export const schemaSha256 = '8e7004722103284c3fb8ff0d87bbc6501a04f106a4869b6bd1083850ca11dd64';
export const metadata = {
  version: 1,
  complete: true,
  operations: {
    '/items': {
      get: {
        parameters: {
          query: { filter: { name: 'filter', in: 'query', style: 'deepObject', explode: true } },
        },
      },
    },
    '/items/{id}': {
      get: {
        parameters: {
          path: { id: { name: 'id', in: 'path', style: 'simple', explode: false, required: true } },
        },
      },
    },
  },
} as unknown as CompiledOpenAPIMetadata;
