import { createHash } from 'node:crypto';
import { createRequire } from 'node:module';
import { dirname, isAbsolute, join, relative, resolve, sep } from 'node:path';
import {
  readFile,
  lstat,
  realpath,
  readdir,
  mkdir,
  mkdtemp,
  rename,
  rm,
  open,
} from 'node:fs/promises';
import openapiTS, { astToString } from 'openapi-typescript';
import { parseDocument } from 'yaml';
import { compileOpenAPIMetadata } from '@openapi-chain/core/metadata';

const require = createRequire(import.meta.url);
const pkg = require('../package.json');
const generatorRequire = createRequire(require.resolve('openapi-typescript'));
const versions = {
  cli: pkg.version,
  runtime: require('@openapi-chain/core/package.json').version,
  generator: require('openapi-typescript/package.json').version,
  typescript: generatorRequire('typescript/package.json').version,
  yaml: require('yaml/package.json').version,
};
const banner = '// Generated by openapi-chain-cli; do not edit.\n';
const filenames = ['schema.d.ts', 'scope.ts', 'metadata.ts', 'manifest.json'];
const hash = (value) => createHash('sha256').update(value).digest('hex');
const json = (value) => `${JSON.stringify(value, null, 2)}\n`;
const record = (value) => value !== null && typeof value === 'object' && !Array.isArray(value);

function localPath(value, label) {
  if (typeof value !== 'string' || !value || /^[a-z][a-z\d+.-]*:\/\//i.test(value)) {
    throw new Error(`${label} must be a local file path.`);
  }
  return value;
}

function validateConfig(config) {
  if (!record(config)) throw new Error('Config must be a JSON object.');
  for (const key of Object.keys(config)) {
    if (!['schema', 'outDir', 'paths', 'onAmbiguousTemplate'].includes(key)) {
      throw new Error(`Unknown config field: ${key}`);
    }
  }
  localPath(config.schema, 'schema');
  localPath(config.outDir, 'outDir');
  if (
    config.paths !== undefined &&
    (!Array.isArray(config.paths) || config.paths.some((path) => typeof path !== 'string'))
  ) {
    throw new Error('paths must be an array of exact OpenAPI path keys.');
  }
  if (
    config.onAmbiguousTemplate !== undefined &&
    !['throw', 'allow'].includes(config.onAmbiguousTemplate)
  ) {
    throw new Error('onAmbiguousTemplate must be throw or allow.');
  }
}

// Reject external references before calling a generator that could fetch them.
// Inspect the full document: full type declarations are generated even with a scope.
function assertLocalReferences(value, active = new Set()) {
  if (typeof value === 'number' && !Number.isFinite(value))
    throw new Error('Schema must contain only JSON-compatible values.');
  if (!value || typeof value !== 'object') return;
  if (active.has(value)) throw new Error('Cyclic YAML aliases are not supported; use local $ref.');
  active.add(value);
  if (typeof value.$ref === 'string' && !value.$ref.startsWith('#')) {
    throw new Error(
      `External $ref is not supported: ${value.$ref}. Bundle the document into one local file first.`,
    );
  }
  for (const child of Object.values(value)) assertLocalReferences(child, active);
  active.delete(value);
}

function inside(path, directory) {
  const rel = relative(directory, path);
  return rel === '' || (!isAbsolute(rel) && rel !== '..' && !rel.startsWith(`..${sep}`));
}

async function exists(path) {
  try {
    return await lstat(path);
  } catch (error) {
    if (error.code === 'ENOENT') return undefined;
    throw error;
  }
}

// Resolve existing ancestors too, so symlinks cannot hide an input/output overlap.
async function canonical(path) {
  if (await exists(path)) return realpath(path);
  return join(await canonical(dirname(path)), relative(dirname(path), path));
}

export async function render(configFile) {
  const configPath = await realpath(resolve(localPath(configFile, 'config')));
  const config = JSON.parse(await readFile(configPath, 'utf8'));
  validateConfig(config);
  const schemaPath = await realpath(resolve(dirname(configPath), config.schema));
  const outDir = resolve(dirname(configPath), config.outDir);
  const outputPath = await canonical(outDir);
  if (inside(configPath, outputPath) || inside(schemaPath, outputPath)) {
    throw new Error('outDir must not contain the config or source schema.');
  }
  const source = (await readFile(schemaPath, 'utf8')).replace(/\r\n/g, '\n');
  let document;
  if (/\.json$/i.test(schemaPath)) document = JSON.parse(source);
  else if (/\.ya?ml$/i.test(schemaPath)) {
    const parsed = parseDocument(source, { uniqueKeys: true });
    if (parsed.errors.length) throw new Error(`Invalid YAML: ${parsed.errors[0].message}`);
    document = parsed.toJS({ maxAliasCount: 100 });
  } else throw new Error('Schema file must use .json, .yaml or .yml.');
  if (
    !record(document) ||
    typeof document.openapi !== 'string' ||
    !/^3\.[01]\./.test(document.openapi)
  ) {
    throw new Error(
      'CLI type generation supports OpenAPI 3.0 and 3.1. OpenAPI 3.2 requires a compatible upstream type generator.',
    );
  }
  assertLocalReferences(document);
  const metadata = compileOpenAPIMetadata(document, {
    ...(config.paths === undefined ? {} : { paths: config.paths }),
    onAmbiguousTemplate: config.onAmbiguousTemplate ?? 'throw',
  });
  const selectedPaths = Object.keys(metadata.operations);
  // Both passes receive the same parsed document, without pruning referenced paths.
  const declarations = astToString(await openapiTS(structuredClone(document), { silent: true }));
  const outputs = {
    'schema.d.ts': banner + declarations,
    'scope.ts': `${banner}import type { paths } from './schema.js';\n\nexport const selectedPaths = ${JSON.stringify(selectedPaths)} as const satisfies readonly (keyof paths)[];\nexport type ScopedPaths = Pick<paths, (typeof selectedPaths)[number]>;\n`,
    'metadata.ts': `${banner}import type { CompiledOpenAPIMetadata } from '@openapi-chain/core/metadata';\n\nexport const metadata = JSON.parse(${JSON.stringify(JSON.stringify(metadata))}) as CompiledOpenAPIMetadata;\n`,
  };
  outputs['manifest.json'] = json({
    formatVersion: 1,
    generator: 'openapi-chain-cli',
    versions,
    schemaSha256: hash(source),
    configSha256: hash(json(config)),
    selectedPaths,
    artifacts: Object.fromEntries(
      Object.entries(outputs).map(([file, content]) => [file, hash(content)]),
    ),
  });
  return { outDir, outputs, selectedPaths };
}

async function inspectOutput(outDir) {
  const stat = await exists(outDir);
  if (!stat) return undefined;
  if (!stat.isDirectory() || stat.isSymbolicLink())
    throw new Error('outDir must be a real directory, not a symlink.');
  const files = await readdir(outDir);
  if (files.some((file) => !filenames.includes(file))) {
    throw new Error('outDir contains unrelated files; use a dedicated generated directory.');
  }
  const contents = {};
  for (const file of files) {
    if (!(await lstat(join(outDir, file))).isFile())
      throw new Error(`Generated artifact must be a regular file: ${file}`);
    contents[file] = await readFile(join(outDir, file), 'utf8');
  }
  if (files.length) {
    let manifest;
    try {
      manifest = JSON.parse(contents['manifest.json']);
    } catch {
      /* Checked below. */
    }
    if (manifest?.generator !== 'openapi-chain-cli' || manifest.formatVersion !== 1) {
      throw new Error('outDir is not owned by openapi-chain-cli; use a new generated directory.');
    }
  }
  return contents;
}

export async function generate(configFile, { check = false } = {}) {
  const result = await render(configFile);
  const { outDir, outputs } = result;
  const compare = (existing) => filenames.filter((file) => existing?.[file] !== outputs[file]);
  if (check) {
    const stale = compare(await inspectOutput(outDir));
    if (stale.length)
      throw new Error(
        `Generated output is stale or missing: ${stale.join(', ')}. Run openapi-chain generate.`,
      );
    return { ...result, changed: false };
  }
  await mkdir(dirname(outDir), { recursive: true });
  const lockPath = `${outDir}.openapi-chain.lock`;
  const lock = await open(lockPath, 'wx').catch((error) => {
    if (error.code === 'EEXIST')
      throw new Error(
        `Generation lock exists: ${lockPath}. Wait for the writer; remove it only if that writer has stopped.`,
      );
    throw error;
  });
  let stage;
  let backup;
  let committed = false;
  try {
    await lock.writeFile(json({ pid: process.pid }));
    if (!compare(await inspectOutput(outDir)).length) return { ...result, changed: false };
    stage = await mkdtemp(join(dirname(outDir), '.openapi-chain-'));
    for (const [file, content] of Object.entries(outputs)) {
      const handle = await open(join(stage, file), 'wx');
      try {
        await handle.writeFile(content);
      } finally {
        await handle.close();
      }
    }
    if (await exists(outDir)) {
      backup = `${stage}.previous`;
      await rename(outDir, backup);
    }
    try {
      await rename(stage, outDir);
      committed = true;
    } catch (error) {
      if (backup) {
        await rename(backup, outDir);
        backup = undefined;
      }
      throw error;
    }
    return { ...result, changed: true };
  } finally {
    if (stage) await rm(stage, { recursive: true, force: true });
    if (backup && committed) await rm(backup, { recursive: true, force: true });
    await lock.close();
    await rm(lockPath, { force: true });
  }
}
